version: "3.8"
# Up DB service
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container-apt
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: apt_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql-network

volumes:
  mysql-data:
    driver: local

networks:
  mysql-network:
    driver: bridge
